# Generated by Django 6.0.3 on 2026-06-01 00:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('investment', 'Investment')], max_length=30)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=15)),
                ('single_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('daily_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('daily_spent_reset_at', models.DateTimeField(blank=True, null=True)),
                ('waqaa_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('freeze_reason', models.TextField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_by', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='BankAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('account_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField()),
                ('result', models.CharField(choices=[('ok', 'OK'), ('fail', 'Fail')], max_length=10)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_audit_log',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('national_id_hmac', models.TextField(unique=True)),
                ('phone_hmac', models.TextField(unique=True)),
                ('email_hmac', models.TextField(blank=True, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('waqaa_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('waqaa_linked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_kyc', 'Pending KYC'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending_kyc', max_length=30)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('prepaid', 'Prepaid')], max_length=20)),
                ('last_four', models.CharField(max_length=4)),
                ('card_number_hash', models.TextField(unique=True)),
                ('expiry_date', models.DateField()),
                ('cardholder_name', models.TextField()),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=15)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_online_enabled', models.BooleanField(default=True)),
                ('is_international', models.BooleanField(default=False)),
                ('pin_hash', models.TextField(blank=True, null=True)),
                ('failed_pin_attempts', models.IntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='inactive', max_length=20)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cards', to='waqaabank.account')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biller_name', models.TextField()),
                ('biller_code', models.CharField(max_length=50)),
                ('bill_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requires_waqaa', models.BooleanField(default=False)),
                ('waqaa_session_id', models.UUIDField(blank=True, null=True)),
                ('waqaa_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bills', to='waqaabank.account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bills', to='waqaabank.client')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='waqaabank.client'),
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField(unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='login_sessions', to='waqaabank.client')),
            ],
            options={
                'db_table': 'login_sessions',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bill_payment', 'Bill Payment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requires_verification', 'Requires Verification'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=30)),
                ('requires_waqaa', models.BooleanField(default=False)),
                ('waqaa_session_id', models.UUIDField(blank=True, null=True)),
                ('waqaa_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('waqaa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('waqaa_verified_by', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sent_transactions', to='waqaabank.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='received_transactions', to='waqaabank.account')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
